package com.bitguiders.hadoop.spark;

import com.google.common.collect.Lists;

import scala.Tuple2;

import org.apache.spark.api.java.function.FlatMapFunction;
import org.apache.spark.api.java.function.Function2;
import org.apache.spark.api.java.function.Function;
import org.apache.spark.api.java.function.PairFunction;
import org.apache.spark.streaming.Duration;
import org.apache.spark.streaming.Durations;
import org.apache.spark.streaming.api.java.JavaDStream;
import org.apache.spark.streaming.api.java.JavaPairDStream;
import org.apache.spark.streaming.api.java.JavaStreamingContext;
import org.apache.spark.streaming.dstream.DStream;

import java.util.Iterator;
import java.util.regex.Pattern;

/**
 * Counts words in UTF8 encoded, '\n' delimited text received from the network every second.
 * Usage: NetworkWordCount <master> <hostname> <port>
 *   <master> is the Spark master URL. In local mode, <master> should be 'local[n]' with n > 1.
 *   <hostname> and <port> describe the TCP server that Spark Streaming would connect to receive data.
 *
 * To run this on your local machine, you need to first run a Netcat server
 *    `$ nc -lk 9999`
 * and then run the example
 *    `$ ./run org.apache.spark.streaming.examples.JavaNetworkWordCount local[2] localhost 9999`
 */
public final class JavaNetworkWordCount {
  private static final Pattern SPACE = Pattern.compile(" ");

  private JavaNetworkWordCount() {
  }

  public static void main(String[] args) throws InterruptedException {
	String arg[] = {"local[2]","localhost","9999"};
	args = arg;
    if (args.length < 3) {
      System.err.println("Usage: JavaNetworkWordCount <master> <hostname> <port>\n" +
          "In local mode, <master> should be 'local[n]' with n > 1");
      System.exit(1);
    }

    //StreamingExamples.setStreamingLogLevels();

    System.out.println("1:reading streams now...");
    // Create the context with a 1 second batch size
    JavaStreamingContext context = new JavaStreamingContext(args[0], "JavaNetworkWordCount",
            Durations.seconds(2), System.getenv("SPARK_HOME"),
            JavaStreamingContext.jarOfClass(JavaNetworkWordCount.class));

    System.out.println("2 creating batchs now...");
    // Create a NetworkInputDStream on target ip:port and count the
    // words in input stream of \n delimited text (eg. generated by 'nc')
    JavaDStream<String> lines = context.socketTextStream(args[1], Integer.parseInt(args[2]));
    System.out.println("3: batch created...");

    for(int i=0;i<5;i++){
    	System.out.println("Printing line "+i+" ");
    	lines.print(i);
    }
    System.out.println("filtering lines now : ");
    lines.filter(new Function<String,Boolean>(){
    	public Boolean call(String line){
    		System.out.println("line => "+line);
    		return true;
    	}
    });
    
    System.out.println("Lines : "+lines.toString());
   
    
    JavaDStream<String> words = lines.flatMap(new FlatMapFunction<String, String>() {
      @Override
      public Iterator<String> call(String x) {
    	  System.out.println("Line :"+x);
        return (Iterator<String>) Lists.newArrayList(SPACE.split(x));
      }
    });
    
    /*JavaPairDStream<String, Integer> wordCounts = words.map(
      new PairFunction<String, String, Integer>() {
        @Override
        public Tuple2<String, Integer> call(String s) {
          return new Tuple2<String, Integer>(s, 1);
        }
      }).reduceByKey(new Function2<Integer, Integer, Integer>() {
        @Override
        public Integer call(Integer i1, Integer i2) {
          return i1 + i2;
        }
      });*/

    //wordCounts.print();
    context.start();
    context.awaitTermination();
  }
}